### ISSUE TITLE
Every /health and /metrics request is logged

### ISSUE THREAD

**Issue by Mortinke** [DataReply/alertmanager-sns-forwarder#1]
### Bug reports:

Steps you follow to reproduce the error:
I deployed the docker image `datareply/alertmanager-sns-forwarder:0.1` on our ECS-cluster without any parameters. Thus, no debug log should be activated

What did you expect to happen instead:
Only important information are logged like `service started successfully`, `ARN prefix could not be detected`, `error while sending sns message`, `listening on:<port>`, ....

What's your theory on why it isn't working:

`gin.Default()` add the Logger and Recovery middleware automaticly, see also [issue #598](https://github.com/gin-gonic/gin/issues/598). We should switch to `gin.New()` and add the `gin.Logger()` and `gin.Recovery()` manually, for example [gin#using-middleware](https://github.com/gin-gonic/gin#using-middleware)

**Comment by olgierdg** [comment]
Thanks, merged.
