### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by evsasha** [DataReply/alertmanager-sns-forwarder#10]
Hello.

1. For run alertmanager-sms-forwarder locally we need set some additional environment variables from AWS:
```
# Specifies an AWS access key associated with an IAM user or role.
AWS_ACCESS_KEY_ID
# Specifies the secret key associated with the access key. This is essentially the "password" for the access key.
AWS_SECRET_ACCESS_KEY
# Specifies the AWS Region to send the request to. 
AWS_REGION
```

Please add this to Readme.

2.  I dont understand why we need to set AWS_REGION when it's van be got from aws_arn/aws_arn/prefix variable?
If region variable is missing:
```
warning msg="MissingRegion: could not find region configuration"
```

**Comment by olgierdg** [comment]
You're right, this should be in readme, thanks, I'll add it. The reason is described in https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html.

However, it's also a good idea to get it from the ARN prefix if it's not available as an env var, but the ARN prefix is. I'll try to implement it.

**Comment by olgierdg** [comment]
Ok, added to the readme. 

I also added code for this in branch [issue-10](/DataReply/alertmanager-sns-forwarder/tree/issue-10). The logic implemented is if region is not configured according to AWS SDK docs, but ARN prefix is provided, then the region will be parsed from the ARN prefix.

The existing functionality of detecting the prefix should not be affected, that is if you'd like the prefix to be detected, you'd have to first provide the region as now described in the readme.

Please check if this would work for you.

**Comment by evsasha** [comment]
Everything works perfectly.

- If you set an empty variable `AWS_REGION=` - it works
- If you do not set a variable `#AWS_REGION=region` - it works
- If you set the wrong region `#AWS_REGION=somethingwrong` - it works too =)

So we don't need to set manually  this variable anymore.

**Comment by olgierdg** [comment]
Great, so I'll merge the changes and close the issue.
