### ISSUE TITLE
Enhance error handling on sns publish

### ISSUE THREAD

**Issue by justin-watkinson-sp** [DataReply/alertmanager-sns-forwarder#14]
### Enhancement Request:

Currently, when any error is observed during the SNS Publish, it appears that it will result in the http.StatusServiceUnavailable being sent back to alertmanager.  Given this is a 5xx class error, it appears to invoke the retry logic within alertmanager, even for cases where it will never succeed.

For example, I've run into an issue where the payload size exceeded 256 KB, which is the current SNS service limit.  It would be preferable in this scenario to emit a 4xx type http response in order to ensure retries are not attempted, as they will not succeed on retry.  This will help reduce calls and potential for back-pressure into alertmanager and Prometheus.

**Comment by justin-watkinson-sp** [comment]
If worthwhile and accepting PRs, happy to take this on and handle all forms of SNS Publish errors with sane defaults.

**Comment by olgierdg** [comment]
Good find, thanks. Sure, definitely accepting PRs, feel free to take this on.
