### ISSUE TITLE
Change User

### ISSUE THREAD

**Issue by christianwoehrle** [DataReply/alertmanager-sns-forwarder#20]
It's more of a feature request

### Bug reports:
Steps you follow to reproduce the error:

On AWS EKS with Kubernetes 1.13 I diabled the default PodSecurityPolicy that allows every pod to run as root.
After that I couldn't start the alertmanager-sns-forwarder as this container runs with the default user (0)

```
kubectl get po 
alertmanager-sns-forwarder-7f4554567d-jw94v       0/1     CreateContainerConfigError   0          10m


kubectl describe po alertmanager-sns-forwarder-7f4554567d-jw94v  

 Warning  Failed     6s (x7 over 78s)  kubelet, ip-172-16-248-158.eu-west-1.compute.internal  Error: container has runAsNonRoot and image will run as root

```

What did you expect to happen instead:

A running container

What's your theory on why it isn't working:

The container should run as non root. 
The fix is simple, if you're interested I'd be happy to provide a PR.

**Comment by olgierdg** [comment]
Thanks, good find, there is no reason to run as root. Please check out if changes in pull request #21 would be enough to resolve this.
