### ISSUE TITLE
Aws library update for IAM roles for service accounts

### ISSUE THREAD

**Issue by christianwoehrle** [DataReply/alertmanager-sns-forwarder#29]
I have used ```alertmanager-sns-forwarder``` with kube2iam in AWS EKS and it has worked fine.

When I switched to IAM roles for service accounts (https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) I got authorization errors when ``` alertmanager-sns-forwarder ``` because the aws libs in this project don't support that new concept yet.

After updating to the current version of the aws libs and switching to go mod this works.

I'd provide a PR if you like to have that update.

**Comment by olgierdg** [comment]
Hi, thanks for the PR, I do however see that there is a quite similar one already, #27. Any chance that one works out for you as well?

**Comment by christianwoehrle** [comment]
Sure, go ahead.

I'll test it when it's merged and I'll close the issue and PR if it works.

**Comment by anthonydahanne** [comment]
hello all - after a quick look at both modularization PR, I believe #30 is slightly cleaner and simpler.

Any reason it's not being merged? thanks

**Comment by olgierdg** [comment]
Ok, #30 was merged.

**Comment by anthonydahanne** [comment]
cool! thanks @olgierdg !
