### ISSUE TITLE
HTML template support

### ISSUE THREAD

**Issue by Mortinke** [DataReply/alertmanager-sns-forwarder#3]
### Feature request

[prometheus_bot](https://github.com/inCaller/prometheus_bot) support [customising messages with template](https://github.com/inCaller/prometheus_bot#customising-messages-with-template). I'd be grateful if the `alertmanager-sns-forwarder` would support this too.

**Comment by olgierdg** [comment]
Ok, I copied the templating logic from prometheus_bot here, please check if this would work for you.
The code is in a branch [issue-3](/DataReply/alertmanager-sns-forwarder/tree/issue-3)

The relevant config parameters should be specified as command line arguments (or env vars), since this app does not use a config file:

template-path (SNS_FORWARDER_TEMPLATE_PATH)
template-time-zone (SNS_FORWARDER_TEMPLATE_TIME_ZONE)
template-time-out-format (SNS_FORWARDER_TEMPLATE_TIME_OUT_FORMAT)
template-split-token (SNS_FORWARDER_TEMPLATE_SPLIT_TOKEN)

**Comment by evsasha** [comment]
Hello, i tested this brunch and it doesn't work.
Issue-3 brunch:
```
Jan 22 11:41:49 vm-10 systemd[1]: Started alertmanager-sns-forwarder.
Jan 22 11:41:49 vm-10 alertmanager-sns-forwarder[20415]: time="2019-01-22T11:41:49+03:00" level=info msg="Load template file:/opt/alertmanager_sns_forwarder/default.tmpl"
Jan 22 11:41:49 vm-10 alertmanager-sns-forwarder[20415]: time="2019-01-22T11:41:49+03:00" level=warning msg="ARN prefix not supplied or wrong, will try to detect"
Jan 22 11:43:49 vm-10 alertmanager-sns-forwarder[20415]: time="2019-01-22T11:43:49+03:00" level=warning msg="ARN prefix could not be detected, underlying problem is: aws metadata api not available. You will need to use the full topic ARN in the POST URL."
Jan 22 11:43:49 vm-10 alertmanager-sns-forwarder[20415]: [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
Jan 22 11:43:49 vm-10 alertmanager-sns-forwarder[20415]: - using env:        export GIN_MODE=release
Jan 22 11:43:49 vm-10 alertmanager-sns-forwarder[20415]: - using code:        gin.SetMode(gin.ReleaseMode)
Jan 22 11:43:49 vm-10 alertmanager-sns-forwarder[20415]: [GIN-debug] Listening and serving HTTP on 0.0.0.0:9087
```

Issue-3 Merged with master:
```
Jan 22 11:34:06 vm-10 systemd[1]: Started alertmanager-sns-forwarder.
Jan 22 11:34:06 vm-10 alertmanager-sns-forwarder[20357]: time="2019-01-22T11:34:06+03:00" level=info msg="Load template file:/opt/alertmanager_sns_forwarder/default.tmpl"
Jan 22 11:34:06 vm-10 alertmanager-sns-forwarder[20357]: [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
Jan 22 11:34:06 vm-10 alertmanager-sns-forwarder[20357]: - using env:        export GIN_MODE=release
Jan 22 11:34:06 vm-10 alertmanager-sns-forwarder[20357]: - using code:        gin.SetMode(gin.ReleaseMode)
Jan 22 11:34:06 vm-10 alertmanager-sns-forwarder[20357]: [GIN-debug] Listening and serving HTTP on 0.0.0.0:9087
Jan 22 11:34:20 vm-10 alertmanager-sns-forwarder[20357]: [GIN] 2019/01/22 - 11:34:20 | 404 |       1.978µs |   192.168.*.* | GET      /favicon.ico
Jan 22 11:34:40 vm-10 alertmanager-sns-forwarder[20357]: [GIN] 2019/01/22 - 11:34:40 | 404 |         886ns |   192.168.*.* | POST     /alert/alertmanager-cmx-test
```

I use default.tmpl file and following variables:
```
SNS_FORWARDER_ADDRESS=0.0.0.0:9087
SNS_FORWARDER_DEBUG=true
SNS_FORWARDER_ARN_PREFIX=***
SNS_FORWARDER_TEMPLATE_PATH=/opt/alertmanager_sns_forwarder/default.tmpl
AWS_ACCESS_KEY_ID=***
AWS_SECRET_ACCESS_KEY=***
AWS_REGION=eu-west-1
```
I tried test with Curl by sending raw text and simple.json file. But anyway got 404. /health and /metrics don't work too.

I need this feature to send SMS, full json is too big for SMS.

**Comment by olgierdg** [comment]
Hi, there was a bug with the gin router initialization which should be fixed now. I just ran the app built from the code from this branch (issue-3) and was able to successfully publish a message according to the template to an SNS topic.

Could you try again after building from the issue-3 branch?

**Comment by evsasha** [comment]
It's work!

**Comment by olgierdg** [comment]
That's great to hear. I've merged the changes into master and I'm closing this issue, since the basic functionality is provided and works.
