### ISSUE TITLE
use  alertmanager-sns-forwarder sms template 

### ISSUE THREAD

**Issue by yishaihl** [DataReply/alertmanager-sns-forwarder#33]
Hey,
i'm trying to use the following attribute: **SNS_FORWARDER_TEMPLATE_PATH**
and use the default **https://github.com/DataReply/alertmanager-sns-forwarder/blob/master/testdata/default.tmpl**
(because i can't send the message json payload via sms because it's huge, e-mail subscription is working properly.)  

but i cant understand which path i should use as the value? 

i so on some post that the default is: /opt/alertmanager_sns_forwarder/default.tmpl (and it's not working)

what am i missing here? 

Thanks,
Yishai.

**Comment by avirtual** [comment]
You're not going to find it in the docker image. You're going to have to mount your own file in a volume and specify the template path as env variable.

**Comment by rashmi-jain-sp** [comment]
I was able to make it work. Let me know if you're still facing the issue.

**Comment by yishaihl** [comment]
Solved

**Comment by yishaihl** [comment]
Solved

**Comment by yishaihl** [comment]
Solved
