### ISSUE TITLE
Error parsing reference: "golang:alpine as builder" is not a valid repository/tag

### ISSUE THREAD

**Issue by asloan7** [DataReply/alertmanager-sns-forwarder#4]
$ docker --version
Docker version 17.03.1-ce, build c6d412e

alertmanager-sns-forwarder]$ docker build -t alertmanager-sns-forwarder:0.1 .
Sending build context to Docker daemon 47.62 kB
Step 1/10 : FROM golang:alpine as builder
Error parsing reference: "golang:alpine as builder" is not a valid repository/tag: invalid reference format

**Comment by olgierdg** [comment]
Issue related to Docker version - https://docs.docker.com/develop/develop-images/multistage-build/ :

`Multi-stage builds are a new feature requiring Docker 17.05 or higher on the daemon and client`

**Comment by olgierdg** [comment]
Closing due to lack of feedback. If the provided explanation is not enough and you'd like some more help, please reopen.
