### ISSUE TITLE
docker build prerequisites?

### ISSUE THREAD

**Issue by asloan7** [DataReply/alertmanager-sns-forwarder#5]
getting errors while trying to do docker build, not sure what the prerequisites are (on a Centos linux).

go test github.com/DataReply/alertmanager-sns-forwarder/...
# runtime/cgo
exec: "gcc": executable file not found in $PATH
FAIL    github.com/DataReply/alertmanager-sns-forwarder [build failed]
FAIL    github.com/DataReply/alertmanager-sns-forwarder/arnutil [build failed]
make: *** [Makefile:16: test] Error 2
The command '/bin/sh -c make all' returned a non-zero code: 2

**Comment by asloan7** [comment]
$ which gcc
/usr/bin/gcc

**Comment by olgierdg** [comment]
PR #6 should resolve this.

**Comment by asloan7** [comment]
This worked, thanks!

**Comment by olgierdg** [comment]
Great, so I'll close this issue.
